sonar.projectName=OWASP Juice Shop

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,frontend/node_modules/**,dist/**,build/**,coverage/**,**/*.test.ts,**/*.spec.ts
